
backend:
  name: git-gateway
  branch: main
local_backend: true
publish_mode: editorial_workflow
site_url: "https://c2lc-project.netlify.app"
media_folder: "src/assets/media"
public_folder: "/assets/media"
collections:
  - name: resources
    label: Coding Resources
    label_singular: Coding Resource
    folder: "src/resources"
    slug: "{{slug}}"
    preview_path: "/learn/resources/{{slug}}"
    editor:
      preview: false
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", timeFormat: false}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Preview Image", name: "metaImage", widget: "image", required: false}
      - {label: "Preview Image Alt Text", name: "metaImageAlt", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Supportive Material"
        name: "supportiveMaterial"
        widget: "list"
        summary: "{{fields.label}}"
        required: false
        fields:
        - {label: "Label", name: "label", widget: "string"}
        - {label: "File", name: "file", widget: "file"}
  - name: activities
    label: Activities at Home
    label_singular: Home Activity
    folder: "src/activities"
    slug: "{{slug}}"
    preview_path: "/learn/activities/{{slug}}"
    editor:
      preview: false
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Type", name: "type", widget: "relation", collection: "siteData", file: "activityTags", value_field: types.*, displayFields: [types.*], search_fields: [types.*]}
      - {label: "Coding Experience Level", name: "experience", widget: "relation", collection: "siteData", file: "activityTags", value_field: experience.*, displayFields: [experience.*], search_fields: [experience.*]}
      - {label: "Subject", name: "subject", widget: "relation", collection: "siteData", file: "activityTags", value_field: subjects.*, displayFields: [subjects.*], search_fields: [subjects.*]}
      - {label: "Related Activities", name: "relatedActivities", widget: "relation", collection: "activities", search_fields: ["title"], value_field: "title", display_fields: ["title"], multiple: true, required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Preview Image", name: "metaImage", widget: "image", required: false}
      - {label: "Preview Image Alt Text", name: "metaImageAlt", widget: "string", required: false}
      - label: "What You Need"
        name: "whatYouNeed"
        widget: "markdown"
        default: "### Tools\n\n### Skills\n\n### Environment\n\n### Support\n\n"
      - label: "Body"
        name: "body"
        widget: "markdown"
        default: "## Objectives\n\n## Description\n\n## Steps\n\n## Tips\n\n## Skill Development\n\n## Level Up!\n\n"
      - label: "Book suggestions"
        name: "books"
        widget: "list"
        summary: "{{fields.title}}"
        required: false
        fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Author", name: "author", widget: "string"}
        - {label: "Cover Image", name: "coverImage", widget: "image"}
        - {label: "Link", name: "link", widget: "string"}
  - name: robotActivities
    label: Activities with Robots
    label_singular: Robot Activity
    folder: "src/robot-activities"
    slug: "{{slug}}"
    preview_path: "/learn/robots/"
    editor:
      preview: false
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Robot", name: "tags", widget: "relation", multiple: true, collection: "siteData", file: "robotActivityTags", value_field: robots.*, displayFields: [robots.*], search_fields: [robots.*]}
      - {label: "Coding Experience Level", name: "experience", widget: "relation", collection: "siteData", file: "robotActivityTags", value_field: experience.*, displayFields: [experience.*], search_fields: [experience.*]}
      - {label: "Topic", name: "topic", widget: "relation", collection: "siteData", file: "robotActivityTags", value_field: topics.*, displayFields: [topics.*], search_fields: [topics.*]}
      - {label: "Related Activities with Robots", name: "relatedRobotActivities", widget: "relation", collection: "robotActivities", search_fields: ["title"], value_field: "title", display_fields: ["title"], multiple: true, required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Preview Image", name: "metaImage", widget: "image", required: false}
      - {label: "Preview Image Alt Text", name: "metaImageAlt", widget: "string", required: false}
      - label: "What You Need"
        name: "whatYouNeed"
        widget: "markdown"
        default: "### Tools\n\n### Skills\n\n### Environment\n\n### Support\n\n"
      - label: "Body"
        name: "body"
        widget: "markdown"
        default: "## Lesson Objectives\n\n## Description\n\n## Steps\n\n## Curriculum Connections\n\n## Accessibility Considerations\n\n## Skill Development"
      - label: "Book suggestions"
        name: "books"
        widget: "list"
        summary: "{{fields.title}}"
        required: false
        fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Author", name: "author", widget: "string"}
        - {label: "Cover Image", name: "coverImage", widget: "image"}
        - {label: "Link", name: "link", widget: "string"}
      - label: "Supportive Material"
        name: "supportiveMaterial"
        widget: "list"
        summary: "{{fields.label}}"
        required: false
        fields:
        - {label: "Label", name: "label", widget: "string"}
        - {label: "File", name: "file", widget: "file"}
  - name: projects
    label: Projects
    label_singular: Project
    folder: "src/projects"
    preview_path: "/community/projects/"
    editor:
      preview: false
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Type", name: "type", widget: "relation", collection: "siteData", file: "projectTags", value_field: types.*, displayFields: [types.*], search_fields: [types.*], required: false}
      - {label: "Category", name: "category", widget: "relation", collection: "siteData", file: "projectTags", value_field: categories.*, displayFields: [categories.*], search_fields: [categories.*]}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Preview Image", name: "metaImage", widget: "image", required: false}
      - {label: "Preview Image Alt Text", name: "metaImageAlt", widget: "string", required: false}
  - name: guides
    label: "Manufacturer’s Guides"
    label_singular: "Manufacturer’s Guide"
    folder: "src/guides"
    preview_path: "/learn/robots/"
    editor:
      preview: false
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Robot", name: "robot", widget: "relation", collection: "siteData", file: "robotActivityTags", value_field: robots.*, displayFields: [robots.*], search_fields: [robots.*]}
      - {label: "Manufacturer", name: "manufacturer", widget: "string"}
      - {label: "Manufacturer Link", name: "manufacturerLink", widget: "string"}
      - {label: "Preview Image", name: "metaImage", widget: "image", required: false}
      - {label: "Preview Image Alt Text", name: "metaImageAlt", widget: "string", required: false}
      - label: "Learning Resources"
        name: "resources"
        widget: "list"
        summary: "{{fields.description}}"
        required: false
        fields:
        - {label: "Description", name: "description", widget: "string"}
        - {label: "Link", name: "link", widget: "string"}
  - name: siteData
    label: Site Data
    files:
      - label: Activity Tags
        name: activityTags
        file: "src/_data/activityTags.json"
        fields:
          - {label: "Types", name: "types", widget: "list"}
          - {label: "Experience Levels", name: "experience", widget: "list"}
          - {label: "Subjects", name: "subjects", widget: "list"}
      - label: Robot Activity Tags
        name: robotActivityTags
        file: "src/_data/robotActivityTags.json"
        fields:
          - {label: "Robots", name: "robots", widget: "list"}
          - {label: "Experience Levels", name: "experience", widget: "list"}
          - {label: "Topics", name: "topics", widget: "list"}
      - label: Project Tags
        name: projectTags
        file: "src/_data/projectTags.json"
        fields:
          - {label: "Categories", name: "categories", widget: "list"}
